### ISSUE TITLE
Launch Task List

### ISSUE THREAD

**Issue by prcutler** [prcutler/the-bootloader#10]
Just brainstorming things that need to happen before launch, there's a couple little things I don't want to forget (that don't need an issue opened)

- [x] Fix subscribe link in 3rd block (Currently links to CPS as a placeholder)
- [x] Test inserting podcast art instead of down arrow in Hero block
- [x] Test inserting embedded episode into either Hero block or its own block
- [x] Update Github sponsors page with show info
- [x] Fix Subscribe button to go to Zencastr landing page (after show is set up in Zencastr pending artwork)
